version: "3.8"

services:
  view:
    build:
      context: .
      dockerfile: view.Dockerfile
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: data/
        target: /data/
    init: true

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - type: bind
        source: data/
        target: /data/
    init: true