version: "3"

services:
  crawler:
    build:
      context: ..
      dockerfile: packages/crawler/dev.Dockerfile
    working_dir: /apps/packages/crawler
    environment:
      DATABASE_URL: postgresql://my-pixiv:password@db:5432/my-pixiv
      CONFIG_PATH: /apps/data/config.json
    volumes:
      - ../:/apps/:delegated
    depends_on:
      db:
        condition: service_healthy
    tty: true
    init: true

  web:
    build:
      context: ..
      dockerfile: packages/web/dev.Dockerfile
    working_dir: /apps/packages/web
    environment:
      DATABASE_URL: postgresql://my-pixiv:password@db:5432/my-pixiv
    volumes:
      - ../:/apps/:delegated
    depends_on:
      - crawler
    tty: true
    init: true
    # port forwardingはlaunch.jsonで行う

  types:
    build:
      context: ..
      dockerfile: packages/types/dev.Dockerfile
    working_dir: /apps/packages/types
    volumes:
      - ../:/apps/:delegated
    tty: true
    init: true

  db:
    build:
      context: ..
      dockerfile: packages/db/Dockerfile
    volumes:
      - ../postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: my-pixiv
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-pixiv
      TZ: "Asia/Tokyo"
    init: true

  pgweb:
    image: sosedoff/pgweb
    environment:
      PGWEB_DATABASE_URL: postgresql://root:password@db:5432/my-pixiv?sslmode=disable
    volumes:
      - ../pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:8081
    depends_on:
      - db
