name: hadolint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  hadolint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file: [view.Dockerfile, api.Dockerfile]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: ${{ matrix.file }}
